/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SkeletonRouteImport } from "./routes/skeleton";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as FundsNewRouteImport } from "./routes/funds.new";
import { Route as ApiElectricFundStatsRouteImport } from "./routes/api/electric/fund-stats";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as ApiAiChatRouteImport } from "./routes/api/ai/chat";

const SkeletonRoute = SkeletonRouteImport.update({
  id: "/skeleton",
  path: "/skeleton",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const FundsNewRoute = FundsNewRouteImport.update({
  id: "/funds/new",
  path: "/funds/new",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiElectricFundStatsRoute = ApiElectricFundStatsRouteImport.update({
  id: "/api/electric/fund-stats",
  path: "/api/electric/fund-stats",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: "/api/ai/chat",
  path: "/api/ai/chat",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/skeleton": typeof SkeletonRoute;
  "/funds/new": typeof FundsNewRoute;
  "/api/ai/chat": typeof ApiAiChatRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/electric/fund-stats": typeof ApiElectricFundStatsRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/skeleton": typeof SkeletonRoute;
  "/funds/new": typeof FundsNewRoute;
  "/api/ai/chat": typeof ApiAiChatRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/electric/fund-stats": typeof ApiElectricFundStatsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/skeleton": typeof SkeletonRoute;
  "/funds/new": typeof FundsNewRoute;
  "/api/ai/chat": typeof ApiAiChatRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/electric/fund-stats": typeof ApiElectricFundStatsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/skeleton"
    | "/funds/new"
    | "/api/ai/chat"
    | "/api/auth/$"
    | "/api/electric/fund-stats";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/skeleton"
    | "/funds/new"
    | "/api/ai/chat"
    | "/api/auth/$"
    | "/api/electric/fund-stats";
  id:
    | "__root__"
    | "/"
    | "/skeleton"
    | "/funds/new"
    | "/api/ai/chat"
    | "/api/auth/$"
    | "/api/electric/fund-stats";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SkeletonRoute: typeof SkeletonRoute;
  FundsNewRoute: typeof FundsNewRoute;
  ApiAiChatRoute: typeof ApiAiChatRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiElectricFundStatsRoute: typeof ApiElectricFundStatsRoute;
}

declare module "@tanstack/solid-router" {
  interface FileRoutesByPath {
    "/skeleton": {
      id: "/skeleton";
      path: "/skeleton";
      fullPath: "/skeleton";
      preLoaderRoute: typeof SkeletonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/funds/new": {
      id: "/funds/new";
      path: "/funds/new";
      fullPath: "/funds/new";
      preLoaderRoute: typeof FundsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/electric/fund-stats": {
      id: "/api/electric/fund-stats";
      path: "/api/electric/fund-stats";
      fullPath: "/api/electric/fund-stats";
      preLoaderRoute: typeof ApiElectricFundStatsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/ai/chat": {
      id: "/api/ai/chat";
      path: "/api/ai/chat";
      fullPath: "/api/ai/chat";
      preLoaderRoute: typeof ApiAiChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkeletonRoute: SkeletonRoute,
  FundsNewRoute: FundsNewRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiElectricFundStatsRoute: ApiElectricFundStatsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
