import { fundStatSchema, type FundStat } from "./schema";

const rawFallbackFundStats = [
  {
    id: "vti",
    symbol: "VTI",
    fundName: "Vanguard Total Stock Market ETF",
    category: "Total Market",
    region: "United States",
    nav: 286.42,
    netAssets: 466_900_000_000,
    expenseRatio: 0.03,
    ytdReturn: 8.72,
    oneYearReturn: 15.28,
    threeYearReturn: 9.91,
    risk: "Moderate",
    asOf: "2026-05-22",
  },
  {
    id: "vxus",
    symbol: "VXUS",
    fundName: "Vanguard Total International Stock ETF",
    category: "International Equity",
    region: "Global ex-US",
    nav: 67.18,
    netAssets: 81_600_000_000,
    expenseRatio: 0.05,
    ytdReturn: 6.34,
    oneYearReturn: 11.02,
    threeYearReturn: 5.84,
    risk: "Moderate",
    asOf: "2026-05-22",
  },
  {
    id: "bnd",
    symbol: "BND",
    fundName: "Vanguard Total Bond Market ETF",
    category: "Core Bond",
    region: "United States",
    nav: 73.91,
    netAssets: 115_700_000_000,
    expenseRatio: 0.03,
    ytdReturn: 2.14,
    oneYearReturn: 4.08,
    threeYearReturn: 1.41,
    risk: "Low",
    asOf: "2026-05-22",
  },
  {
    id: "qqqm",
    symbol: "QQQM",
    fundName: "Invesco NASDAQ 100 ETF",
    category: "Large Growth",
    region: "United States",
    nav: 216.77,
    netAssets: 46_200_000_000,
    expenseRatio: 0.15,
    ytdReturn: 12.67,
    oneYearReturn: 21.48,
    threeYearReturn: 14.73,
    risk: "High",
    asOf: "2026-05-22",
  },
  {
    id: "schd",
    symbol: "SCHD",
    fundName: "Schwab US Dividend Equity ETF",
    category: "Dividend Equity",
    region: "United States",
    nav: 82.36,
    netAssets: 67_100_000_000,
    expenseRatio: 0.06,
    ytdReturn: 4.95,
    oneYearReturn: 9.84,
    threeYearReturn: 7.63,
    risk: "Moderate",
    asOf: "2026-05-22",
  },
  {
    id: "vwo",
    symbol: "VWO",
    fundName: "Vanguard FTSE Emerging Markets ETF",
    category: "Emerging Markets",
    region: "Emerging Markets",
    nav: 48.54,
    netAssets: 78_400_000_000,
    expenseRatio: 0.08,
    ytdReturn: 7.41,
    oneYearReturn: 13.36,
    threeYearReturn: 3.26,
    risk: "Elevated",
    asOf: "2026-05-22",
  },
] satisfies Array<FundStat>;

export const fallbackFundStats = rawFallbackFundStats.map((fund) => fundStatSchema.parse(fund));
